FROM ruby:3.2.2-alpine

RUN apk update && \
    apk add build-base curl<%= ' postgresql-dev' if postgres? -%> coreutils npm git jq && \
    rm -rf /var/cache/apk/

RUN npm install -g @apollo/rover

ENV RAILS_ENV=production

COPY Gemfile Gemfile.lock ./
RUN gem install bundler:2.4.12 && \
    bundle config set without 'development test' && \
    bundle install

RUN mkdir /app
WORKDIR /app
COPY . .

CMD ["rails", "server", "-b", "0.0.0.0"]
