---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: "{{ .Release.Name }}"
  annotations:
    force-sync: "{{ now }}"
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "1"
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secrets-manager
    kind: ClusterSecretStore
  target:
    name: "{{ .Release.Name }}"
  dataFrom:
  - extract:
      key: "{{ .Values.env }}/{{ .Release.Name }}"
