name: Dev build and deploy

on: workflow_dispatch

jobs:
  build:
    uses: ./.github/workflows/build.yml
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  deploy:
    uses: ./.github/workflows/deploy.yml
    needs: build
    with:
      env: dev
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      GHA_ACCESS_TOKEN: ${{ secrets.GHA_ACCESS_TOKEN }}
