name: Stage + prod build and deploy

on:
  push:
    branches: [main]

jobs:
  test:
    uses: ./.github/workflows/test.yml
    secrets:
      CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}
      APOLLO_KEY_API: ${{ secrets.APOLLO_KEY_API }}
  build:
    uses: ./.github/workflows/build.yml
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  deploy:
    strategy:
      matrix:
        env: [stage, prod]
    uses: ./.github/workflows/deploy.yml
    needs: [test, build]
    with:
      env: ${{ matrix.env }}
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      GHA_ACCESS_TOKEN: ${{ secrets.GHA_ACCESS_TOKEN }}
