name: Run tests for PR
on:
  pull_request:
    types: [opened, synchronize]
    branches:
      - main

jobs:
  test:
    uses: ./.github/workflows/test.yml
    secrets:
      CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}
      APOLLO_KEY_API: ${{ secrets.APOLLO_KEY_API }}
